"""add command jobs

Revision ID: 0b38e47e6e81
Revises: 693b3a18943d
Create Date: 2026-07-23 15:42:10.502532
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0b38e47e6e81'
down_revision: Union[str, Sequence[str], None] = '693b3a18943d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screening_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('ontology_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_screening_job_status_created', 'screening_jobs', ['status', 'created_at'], unique=False)
    op.create_table('command_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('raw_command', sa.Text(), nullable=False),
    sa.Column('parsed_action', sa.String(length=64), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['screening_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_command_actor_created', 'command_executions', ['actor', 'created_at'], unique=False)
    op.create_index(op.f('ix_command_executions_job_id'), 'command_executions', ['job_id'], unique=False)
    op.create_table('monitored_objects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('space_object_id', sa.String(length=36), nullable=False),
    sa.Column('added_by', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['space_object_id'], ['space_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_objects_space_object_id'), 'monitored_objects', ['space_object_id'], unique=True)
    op.create_table('screening_job_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['screening_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'sequence', name='uq_job_event_sequence')
    )
    op.create_index('ix_job_event_job_sequence', 'screening_job_events', ['job_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_screening_job_events_job_id'), 'screening_job_events', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_job_events_job_id'), table_name='screening_job_events')
    op.drop_index('ix_job_event_job_sequence', table_name='screening_job_events')
    op.drop_table('screening_job_events')
    op.drop_index(op.f('ix_monitored_objects_space_object_id'), table_name='monitored_objects')
    op.drop_table('monitored_objects')
    op.drop_index(op.f('ix_command_executions_job_id'), table_name='command_executions')
    op.drop_index('ix_command_actor_created', table_name='command_executions')
    op.drop_table('command_executions')
    op.drop_index('ix_screening_job_status_created', table_name='screening_jobs')
    op.drop_table('screening_jobs')
    # ### end Alembic commands ###
