"""initial SSA ontology

Revision ID: 693b3a18943d
Revises:
Create Date: 2026-07-23 14:12:19.503973
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '693b3a18943d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('previous_state', sa.JSON(), nullable=False),
    sa.Column('new_state', sa.JSON(), nullable=False),
    sa.Column('data_versions', sa.JSON(), nullable=False),
    sa.Column('model_versions', sa.JSON(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('approval_status', sa.String(length=32), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_actions_action_type'), 'audit_actions', ['action_type'], unique=False)
    op.create_index('ix_audit_entity_time', 'audit_actions', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
    op.create_table('lineage_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upstream_type', sa.String(length=64), nullable=False),
    sa.Column('upstream_id', sa.String(length=36), nullable=False),
    sa.Column('downstream_type', sa.String(length=64), nullable=False),
    sa.Column('downstream_id', sa.String(length=36), nullable=False),
    sa.Column('relationship', sa.String(length=128), nullable=False),
    sa.Column('transformation', sa.String(length=255), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lineage_downstream', 'lineage_edges', ['downstream_type', 'downstream_id'], unique=False)
    op.create_index('ix_lineage_upstream', 'lineage_edges', ['upstream_type', 'upstream_id'], unique=False)
    op.create_table('screening_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('propagator', sa.String(length=64), nullable=False),
    sa.Column('propagator_version', sa.String(length=64), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('input_versions', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('space_objects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('norad_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('orbit_class', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_space_objects_norad_id'), 'space_objects', ['norad_id'], unique=True)
    op.create_table('conjunction_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('screening_run_id', sa.String(length=36), nullable=True),
    sa.Column('primary_object_id', sa.String(length=36), nullable=False),
    sa.Column('secondary_object_id', sa.String(length=36), nullable=False),
    sa.Column('tca', sa.DateTime(timezone=True), nullable=False),
    sa.Column('miss_distance_km', sa.Float(), nullable=False),
    sa.Column('relative_speed_km_s', sa.Float(), nullable=False),
    sa.Column('radial_km', sa.Float(), nullable=True),
    sa.Column('along_track_km', sa.Float(), nullable=True),
    sa.Column('cross_track_km', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_object_id'], ['space_objects.id'], ),
    sa.ForeignKeyConstraint(['screening_run_id'], ['screening_runs.id'], ),
    sa.ForeignKeyConstraint(['secondary_object_id'], ['space_objects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screening_run_id', 'primary_object_id', 'secondary_object_id', 'tca', name='uq_event_run_pair_tca')
    )
    op.create_index(op.f('ix_conjunction_events_primary_object_id'), 'conjunction_events', ['primary_object_id'], unique=False)
    op.create_index(op.f('ix_conjunction_events_screening_run_id'), 'conjunction_events', ['screening_run_id'], unique=False)
    op.create_index(op.f('ix_conjunction_events_secondary_object_id'), 'conjunction_events', ['secondary_object_id'], unique=False)
    op.create_index('ix_event_tca_status', 'conjunction_events', ['tca', 'status'], unique=False)
    op.create_table('element_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('space_object_id', sa.String(length=36), nullable=False),
    sa.Column('line1', sa.String(length=80), nullable=False),
    sa.Column('line2', sa.String(length=80), nullable=False),
    sa.Column('epoch', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parser_version', sa.String(length=64), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('raw_payload_uri', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['space_object_id'], ['space_objects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('space_object_id', 'content_sha256', name='uq_element_object_content')
    )
    op.create_index('ix_element_object_epoch', 'element_sets', ['space_object_id', 'epoch'], unique=False)
    op.create_index(op.f('ix_element_sets_space_object_id'), 'element_sets', ['space_object_id'], unique=False)
    op.create_table('sensor_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('space_object_id', sa.String(length=36), nullable=False),
    sa.Column('sensor', sa.String(length=255), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frame', sa.String(length=32), nullable=False),
    sa.Column('position_km', sa.JSON(), nullable=False),
    sa.Column('velocity_km_s', sa.JSON(), nullable=True),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['space_object_id'], ['space_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_observation_object_time', 'sensor_observations', ['space_object_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_sensor_observations_space_object_id'), 'sensor_observations', ['space_object_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('rule', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('delivery_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['conjunction_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_event_id'), 'alerts', ['event_id'], unique=False)
    op.create_table('ephemeris_samples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('screening_run_id', sa.String(length=36), nullable=False),
    sa.Column('space_object_id', sa.String(length=36), nullable=False),
    sa.Column('element_set_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frame', sa.String(length=32), nullable=False),
    sa.Column('x_km', sa.Float(), nullable=False),
    sa.Column('y_km', sa.Float(), nullable=False),
    sa.Column('z_km', sa.Float(), nullable=False),
    sa.Column('vx_km_s', sa.Float(), nullable=False),
    sa.Column('vy_km_s', sa.Float(), nullable=False),
    sa.Column('vz_km_s', sa.Float(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['element_set_id'], ['element_sets.id'], ),
    sa.ForeignKeyConstraint(['screening_run_id'], ['screening_runs.id'], ),
    sa.ForeignKeyConstraint(['space_object_id'], ['space_objects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screening_run_id', 'space_object_id', 'timestamp', name='uq_ephemeris_run_object_time')
    )
    op.create_index('ix_ephemeris_object_time', 'ephemeris_samples', ['space_object_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_ephemeris_samples_screening_run_id'), 'ephemeris_samples', ['screening_run_id'], unique=False)
    op.create_index(op.f('ix_ephemeris_samples_space_object_id'), 'ephemeris_samples', ['space_object_id'], unique=False)
    op.create_table('maneuver_scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('space_object_id', sa.String(length=36), nullable=False),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delta_v_r_m_s', sa.Float(), nullable=False),
    sa.Column('delta_v_i_m_s', sa.Float(), nullable=False),
    sa.Column('delta_v_c_m_s', sa.Float(), nullable=False),
    sa.Column('resulting_miss_distance_km', sa.Float(), nullable=True),
    sa.Column('resulting_probability_of_collision', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('simulation_model_version', sa.String(length=128), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['conjunction_events.id'], ),
    sa.ForeignKeyConstraint(['space_object_id'], ['space_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maneuver_scenarios_event_id'), 'maneuver_scenarios', ['event_id'], unique=False)
    op.create_table('monitoring_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['conjunction_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_cases_event_id'), 'monitoring_cases', ['event_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('probability_of_collision', sa.Float(), nullable=False),
    sa.Column('uncertainty', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['conjunction_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assessment_event_created', 'risk_assessments', ['event_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_risk_assessments_event_id'), 'risk_assessments', ['event_id'], unique=False)
    op.create_table('operator_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('selected_action', sa.String(length=255), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('approver', sa.String(length=255), nullable=True),
    sa.Column('approval_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['monitoring_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_decisions_case_id'), 'operator_decisions', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operator_decisions_case_id'), table_name='operator_decisions')
    op.drop_table('operator_decisions')
    op.drop_index(op.f('ix_risk_assessments_event_id'), table_name='risk_assessments')
    op.drop_index('ix_assessment_event_created', table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_monitoring_cases_event_id'), table_name='monitoring_cases')
    op.drop_table('monitoring_cases')
    op.drop_index(op.f('ix_maneuver_scenarios_event_id'), table_name='maneuver_scenarios')
    op.drop_table('maneuver_scenarios')
    op.drop_index(op.f('ix_ephemeris_samples_space_object_id'), table_name='ephemeris_samples')
    op.drop_index(op.f('ix_ephemeris_samples_screening_run_id'), table_name='ephemeris_samples')
    op.drop_index('ix_ephemeris_object_time', table_name='ephemeris_samples')
    op.drop_table('ephemeris_samples')
    op.drop_index(op.f('ix_alerts_event_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_sensor_observations_space_object_id'), table_name='sensor_observations')
    op.drop_index('ix_observation_object_time', table_name='sensor_observations')
    op.drop_table('sensor_observations')
    op.drop_index(op.f('ix_element_sets_space_object_id'), table_name='element_sets')
    op.drop_index('ix_element_object_epoch', table_name='element_sets')
    op.drop_table('element_sets')
    op.drop_index('ix_event_tca_status', table_name='conjunction_events')
    op.drop_index(op.f('ix_conjunction_events_secondary_object_id'), table_name='conjunction_events')
    op.drop_index(op.f('ix_conjunction_events_screening_run_id'), table_name='conjunction_events')
    op.drop_index(op.f('ix_conjunction_events_primary_object_id'), table_name='conjunction_events')
    op.drop_table('conjunction_events')
    op.drop_index(op.f('ix_space_objects_norad_id'), table_name='space_objects')
    op.drop_table('space_objects')
    op.drop_table('screening_runs')
    op.drop_index('ix_lineage_upstream', table_name='lineage_edges')
    op.drop_index('ix_lineage_downstream', table_name='lineage_edges')
    op.drop_table('lineage_edges')
    op.drop_index('ix_audit_entity_time', table_name='audit_actions')
    op.drop_index(op.f('ix_audit_actions_action_type'), table_name='audit_actions')
    op.drop_table('audit_actions')
    # ### end Alembic commands ###
